[package]
name = "least"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.17"
crossterm = "0.22"
clap = { version = "3.0.14", features = ["derive"] }
human_bytes = { version = "0.3", features = ["fast"] }
